name = "tmg-ucm"
main = "worker/dist/index.mjs"

account_id = "b4adf6cfdac0918eb6aa5ad033da0747"
workers_dev = true

compatibility_date = "2022-06-13"
compatibility_flags = []

[build]
command = "NODE_ENV=development node ./build.mjs"
cwd = "worker"
watch_dir = "worker/routes"


[env.stage.build]
command = "NODE_ENV=stage npm run build"

[env.production.build]
command = "NODE_ENV=production npm run build"


[vars]
UPSTREAM = "http://localhost:3000"
API_ENDPOINT = "https://api.telegraph.co.uk"
CONTENT_ENDPOINT = "https://www.telegraph.co.uk"
CACHE_GEN = 0

[env.stage.vars]
UPSTREAM = "https://main--tmg-ucm--hlxsites.hlx.live"
API_ENDPOINT = "https://api.telegraph.co.uk"
CONTENT_ENDPOINT = "https://www.telegraph.co.uk"
CACHE_GEN = 0

[env.production.vars]
UPSTREAM = "https://main--tmg-ucm--hlxsites.hlx.live"
API_ENDPOINT = "https://api.telegraph.co.uk"
CONTENT_ENDPOINT = "https://www.telegraph.co.uk"
CACHE_GEN = 0

# The necessary secrets are:
# - API_KEY
# Run `wrangler secret put <NAME> <VALUE>` for each of these